### ISSUE TITLE
sudo apt autoclean

### ISSUE THREAD

**Issue by Goddard** [pop-os/kernelstub#32]
update-initramfs: Generating /boot/initrd.img-5.0.0-13-generic
kernelstub.Config    : INFO     Looking for configuration...
kernelstub.Drive     : ERROR    Could not get a UUID for the a filesystem. This is a critical error and we cannot continue
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 59, in __init__
    self.root_uuid = self.get_uuid(self.root_fs[5:])
  File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 115, in get_uuid
    raise UUIDNotFoundError
kernelstub.drive.UUIDNotFoundError
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 177
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

apt-cache policy kernelstub
kernelstub:
  Installed: 3.1.0~1539360058~19.04~64d0caf
  Candidate: 3.1.0~1539360058~19.04~64d0caf
  Version table:
 *** 3.1.0~1539360058~19.04~64d0caf 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main i386 Packages
        100 /var/lib/dpkg/status

**Comment by Goddard** [comment]
looks fixed.
